### ISSUE TITLE
Pairing doesn't generate feedback, notifications arrive but can't be seen.

### ISSUE THREAD

**Issue by MwithM** [bisq-network/bisqremote_Android#11]
Phone redmi 8, MIUI 11.
When device is paired with the token, there's no reaction, closing and opening the app takes you again to initial screen with options "pair" and "learn more". Notifications arrive for price alerts. An iOs user has the same problem and reported that trade notifications work. When you press a notification, it takes you again to the initial screen so no info displayed.

**Comment by phredrick42** [comment]
I am having the same problem with initial pairing.   Looks like mobile app receives the notification, but is unable to download the token.   
![image](https://user-images.githubusercontent.com/32398885/100523659-b146ab80-3177-11eb-9872-6338861cfc34.png)

Is this a problem Bisq application side, i.e., the mobile app is unable to access the Bisq hidden tor service?

I tried on my iPad and I can't get it to pair either, which leads me to believe its not a mobile app issue.  Issue with iOS also reported here https://github.com/bisq-network/bisq/issues/2496

Any insights about this problem?
