### ISSUE TITLE
Allow to set the timezone

### ISSUE THREAD

**Issue by Android-X13** [bisq-network/bisqremote_Android#30]
Events on Bisq app are recorded in UTC+0 timezone. Would it be possible for a user to configure the timezone he chooses?

I thought that the app is reporting the time of an event exactly as received by Bisq desktop, however it seems that the desktop app uses the system's preferred timezone (by the way I don't think there's a way in Bisq desktop to set the timezone, at least I can't find any setting).

So the mobile app converts the time received to UTC+0?

**Comment by abhiShandy** [comment]
I'm interested in fixing this.

In the first step, I would like to use the local timezone by default.

In the second step, I would give the option to change the timezone.

**Comment by devinbileck** [comment]
Hi @abhiShandy.
@Android-X13 already has an open PR that will use the system's default timezone. It seems that he will be getting back to completing it soon.
If you are interested in implementing a feature within the app to specify the displayed time zone or format, then feel free to open a PR!
